version: '3'

services:
  client:
    build:
      context: ../
      dockerfile: dev/Dockerfile
    environment:
      REACT_APP_WEBSITE_NAME: Docker Boilerplate
    ports:
      - 3000:3000
    volumes:
      - ../:/app
